"""
make_data.py — emit the corpus string lists into data/ (CPU, no model).

Ships ONLY derived/public-domain material:
  - the barbarous-name *strings* (public-domain ancient attestations) + our analysis
    tags (family, theonym flag, structure tags, contamination score, source ID),
  - our own generated anchor controls (names / words / random).
NO copyrighted Betz edition text (translations/apparatus) is redistributed; PGM spell
IDs are facts, not copyrightable. The model-dependent token-matched controls
(`v_token_match`) are regenerated deterministically (seed 0) by the notebook pipeline.

The canonical definitions live in the notebook generator (src/build_notebook.py); this
module execs the torch-free corpus + anchor cells from the built notebook so the shipped
data provably matches the run.
"""
import json, re, random, os

NB = os.path.join(os.path.dirname(__file__), "..", "notebooks",
                  "voces_residual_stream_v6_voces-specificity.ipynb")

def _exec_cell(ns, marker):
    nb = json.load(open(NB))
    for c in nb["cells"]:
        if c["cell_type"] != "code":
            continue
        src = "".join(c["source"])
        if marker in src:
            # strip notebook-only print noise is unnecessary; cells are torch-free here
            exec(compile(src, f"<cell:{marker}>", "exec"), ns)
            return
    raise RuntimeError(f"cell with marker {marker!r} not found in {NB}")

def main():
    ns = {"random": random}
    random.seed(0)
    _exec_cell(ns, "VOCES_RAW = [")     # corpus: VOCES_RAW, to_greek, contamination_T, ATTESTED_GREEK, SOURCE, THEONYM_ROOTS
    _exec_cell(ns, "NAMES_LAT = [")     # anchors: NAMES_LAT, WORDS_LAT, RANDOM_LAT, cohorts_greek

    VOCES_RAW   = ns["VOCES_RAW"]
    to_greek    = ns["to_greek"]
    contam      = ns["contamination_T"]
    ATTESTED    = ns["ATTESTED_GREEK"]
    SOURCE      = ns["SOURCE"]
    ROOTS       = ns["THEONYM_ROOTS"]

    out = os.path.join(os.path.dirname(__file__), "..", "data")
    os.makedirs(out, exist_ok=True)

    # voces.jsonl — one derived attestation per line
    with open(os.path.join(out, "voces.jsonl"), "w") as f:
        for lat, fam, theo, tags in VOCES_RAW:
            rec = dict(
                latin=lat,
                greek=ATTESTED.get(lat, to_greek(lat)),
                greek_is_authentic=("attested_greek" in tags),
                family=fam,
                theonym_bearing=bool(theo),
                structure_tags=tags,
                contamination_T=round(contam(lat), 4),
                length=len(lat),
                source=SOURCE.get(lat, "curated-from-PGM-knowledge"),
            )
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    json.dump(ROOTS, open(os.path.join(out, "theonym_roots.json"), "w"),
              ensure_ascii=False, indent=1)
    json.dump(dict(name_controls=ns["NAMES_LAT"], word_baseline=ns["WORDS_LAT"],
                   random_seed0=ns["RANDOM_LAT"]),
              open(os.path.join(out, "anchor_controls.json"), "w"),
              ensure_ascii=False, indent=1)

    n = len(VOCES_RAW)
    print(f"data/voces.jsonl           : {n} voces "
          f"({sum(v[2] for v in VOCES_RAW)} theonym-bearing, "
          f"{sum('attested_greek' in v[3] for v in VOCES_RAW)} authentic-Greek)")
    print(f"data/theonym_roots.json    : {len(ROOTS)} roots")
    print(f"data/anchor_controls.json  : {len(ns['NAMES_LAT'])} names / "
          f"{len(ns['WORDS_LAT'])} words / {len(ns['RANDOM_LAT'])} random")
    print("token-matched controls (v_token_match) are model-dependent -> regenerated by the notebook (seed 0).")

if __name__ == "__main__":
    main()
